### ISSUE TITLE
Original source explanation and thanks.

### ISSUE THREAD

**Issue by cruduxcru0** [Falcosoft/vstdriver#3]
Just recently I read over the VOGONS thread: love what you did, figured its time for a explanation.

1) Yeah, I only have the 2011 source (I have it on my own internal privately hosted Git), kode54 had the rest and they are long since AWOL. Apparently they switched to MacOSX and they are working on their own music player including MIDI support, so Windows to them just doesn't exist.
2) I been AWOL too since MIDI back then for games and apps no longer interested me, hence to me no point doing updates. Lately though the need for MIDI came back since been working on something that requires MIDI output support, so this driver has been a massive help with working on that.
3) Thanks for Herman and you doing updates. I really appreciated you picking up the slack.
4) I have been long since embarrassed by the code I did back then, another reason why I stopped. Its a common issue I continue to grapple with: I have zero faith and confidence in what I code **at all**, and am continually embarrassed by its mere existence to this very day.

**Comment by Falcosoft** [comment]
Hi,
Thanks for your comment!
Since I'm not a native C/C++ speaker I'm not an authority to judge code quality by modern standards. Because of this I use a more pragmatic approach: for me good code is such a code that is easy to read/understand and easy to work with. In this sense your code is definitely good :). And I think the whole Midi oriented retro community (including myself) is very grateful you shared it with us.
