### ISSUE TITLE
S-YXG2006LE VSTi bugged in VST MIDI Driver

### ISSUE THREAD

**Issue by skyrain128** [Falcosoft/vstdriver#4]
S-YXG2006LE VSTi bugged in VST MIDI Driver
When playing PASSPORT.MID file, the MIDI is bugged when loading S-YXG2006LE VSTi with VST MIDI Driver
The bug doesn't appear when loading same VSTi on MIDI Player 6.2

The VSTi file, MIDI file and my MP3 recording files are included in the zip file
[SYXG_bug.zip](https://github.com/Falcosoft/vstdriver/files/14101965/SYXG_bug.zip)

Sorry for my bad English grammer...

**Comment by Falcosoft** [comment]
Hi,
No problem, I have understood your problem perfectly. But the truth is this is not a bug in the driver. 
By default S-YXG2006LE plugin starts in XG mode (you cannot see this since it has no GUI/Editor dialog). 
And in XG mode the plugin only considers a channel to be a Drum channel if the channel's Bank MSB is set to 127.
In case of this plugin this is also true for default Drum channel 10.
Since PASSPORT.MID is not an XG Midi file it sets Bank MSB on channel 10 to 0. Thus the plugin threats channel 10 as a melodic channel.
**Solution:**
You should set the Midi mode to be either GM or GS. In Both GM and GS mode the plugin keeps channel 10 to be a drum channel regardless what Bank MSB value is set on channel 10.
You can send GM/GS reset SysEx messages to the plugin either from the player (e.g. Midi Player 6.2) or from VST Midi driver's system tray menu.

**Comment by skyrain128** [comment]
Both GM reset used but GM reset doesn't work on the driver

**Comment by skyrain128** [comment]
When playing with GM reset, it sounds fine
But after the music ends, when replay the music, it's messed up again...
Maybe the plugin's settings return to XG mode when the music ends?

**Comment by skyrain128** [comment]
Is there any way to make the plugin persist in GM mode?

**Comment by Falcosoft** [comment]
Window Media Player unloads the driver after every Midi file on the playlist and also it unloads the driver when you press stop.
So yes, it resets the plugin to XG mode every time playback is stopped/finished.
To be honest I do not really understand why anyone uses WMP for Midi playback since WMP is the dumbest Midi player you can find.  
You should use a more intelligent Midi player that can send the SysEx reset of your choice especially when you deal with such peculiar plugins as S-YXG2006LE.

But here is a test version of the driver that treats S-YXG2006LE similarly to SC-VA (that is it keeps the plugin in memory even if the Midi client sends a close request).
Replaying works in WMP with this problematic Midi file after you sent a GM/GS reset.
But be aware that if you play an XG Midi file that sends an explicit XG reset your Passport.MID will sound bad again. 
So overall the best choice is not to use WMP for Midi playback (especially do not use WMP with this plugin).

[vstmididrv_230_test.zip](https://github.com/Falcosoft/vstdriver/files/14109729/vstmididrv_230_test.zip)

**Comment by Falcosoft** [comment]
Hi, 
I have figured out what would be a better solution:
Similarly to Midi Player the last used/selected SysEx reset is always sent when the synth is loaded. So this way you can select reset mode only once and it is always applied (in case of WMP after every playback stop)
New test version:
[vstmididrv_2301_test.zip](https://github.com/Falcosoft/vstdriver/files/14137057/vstmididrv_2301_test.zip)
